# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sbcCGwYdNKeYSaA38crU8_PXGYMMJStV
"""

! pip install diffusers transformers accelerate peft

from diffusers import AutoPipelineForText2Image
import torch
from google.colab import drive
drive.mount('/content/drive')
# load pre-trained model
pipeline = AutoPipelineForText2Image.from_pretrained("samiam/sd-v1-5_vae-pruned", torch_dtype=torch.float16).to("cuda")
# load LoRA weights
pipeline.load_lora_weights("drive/My Drive/Loras/0/output/", weight_name="0-10.safetensors")
# remove NSFW filter (dermoscopic images get flagged as NSFW most of the time)
pipeline.safety_checker = lambda images, clip_input: (images, [False] * len(images))

# generation prompt
prompt = "actinic keratosis image"
for i in range(1,51,1):
  image = pipeline(prompt).images[0]
  image.save("drive/My Drive/GeneratedImages/actinic keratosis/test_"+str(i)+".png")